import React from 'react';
import { Report } from '../../../types';
import { FileText, Download, Calendar, User, Clock, CheckCircle, AlertCircle, XCircle } from 'lucide-react';

interface ReportViewerProps {
  report: Report;
  onDownload?: (id: string) => void;
  onClose?: () => void;
}

export const ReportViewer: React.FC<ReportViewerProps> = ({
  report,
  onDownload,
  onClose,
}) => {
  const statusColors = {
    PENDING: 'bg-amber-50 text-amber-700 border-amber-200',
    COMPLETED: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    FAILED: 'bg-red-50 text-red-700 border-red-200',
  };

  const formatType = (type: string) => {
    return type.split('_').map((word) => word.charAt(0) + word.slice(1).toLowerCase()).join(' ');
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const StatusIcon =
    report.status === 'COMPLETED'
      ? CheckCircle
      : report.status === 'FAILED'
      ? XCircle
      : AlertCircle;

  return (
    <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-forest-500 to-forest-600 px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center">
              <FileText className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">{report.title}</h2>
              <p className="text-sm text-white/80">{formatType(report.type)}</p>
            </div>
          </div>
          <span
            className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold border ${statusColors[report.status]}`}
          >
            <StatusIcon className="w-3.5 h-3.5" />
            {report.status}
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="p-6 space-y-6">
        {/* Date Range */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-gray-50 rounded-xl p-4">
            <div className="flex items-center gap-2 text-sm text-gray-500 mb-1">
              <Calendar className="w-4 h-4" />
              Start Date
            </div>
            <p className="font-semibold text-gray-900">
              {formatDate(report.dateRange.start)}
            </p>
          </div>
          <div className="bg-gray-50 rounded-xl p-4">
            <div className="flex items-center gap-2 text-sm text-gray-500 mb-1">
              <Calendar className="w-4 h-4" />
              End Date
            </div>
            <p className="font-semibold text-gray-900">
              {formatDate(report.dateRange.end)}
            </p>
          </div>
        </div>

        {/* Report Info */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-sm text-gray-500 mb-1">Generated By</p>
            <div className="flex items-center gap-2">
              <User className="w-4 h-4 text-gray-400" />
              <span className="font-medium text-gray-900">
                {report.generatorName || report.generatedBy}
              </span>
            </div>
          </div>
          <div>
            <p className="text-sm text-gray-500 mb-1">Generated At</p>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4 text-gray-400" />
              <span className="font-medium text-gray-900">
                {new Date(report.generatedAt).toLocaleString()}
              </span>
            </div>
          </div>
        </div>

        {/* Format */}
        <div>
          <p className="text-sm text-gray-500 mb-2">Format</p>
          <span className="inline-block px-3 py-1.5 bg-forest-50 text-forest-700 rounded-lg text-sm font-medium">
            {report.data?.format || 'PDF'}
          </span>
        </div>

        {/* Report Data Preview */}
        {report.data && report.data.summary && (
          <div className="border border-gray-200 rounded-xl p-4">
            <h3 className="font-semibold text-gray-900 mb-3">Summary</h3>
            <p className="text-sm text-gray-600 whitespace-pre-line">
              {report.data.summary}
            </p>
          </div>
        )}

        {/* Key Metrics */}
        {report.data?.metrics && (
          <div className="border border-gray-200 rounded-xl p-4">
            <h3 className="font-semibold text-gray-900 mb-3">Key Metrics</h3>
            <div className="grid grid-cols-2 gap-3">
              {Object.entries(report.data.metrics).map(([key, value]) => (
                <div key={key} className="bg-gray-50 rounded-lg p-3">
                  <p className="text-xs text-gray-500 capitalize mb-1">
                    {key.replace(/([A-Z])/g, ' $1').trim()}
                  </p>
                  <p className="text-lg font-bold text-gray-900">{String(value)}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Expiry */}
        {report.expiresAt && (
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-3">
            <p className="text-sm text-amber-800">
              <strong>Note:</strong> This report will expire on{' '}
              {formatDate(report.expiresAt)}
            </p>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex gap-3 px-6 py-4 bg-gray-50 border-t border-gray-200">
        {onClose && (
          <button
            onClick={onClose}
            className="flex-1 px-4 py-2.5 border border-gray-300 text-gray-700 font-medium rounded-xl hover:bg-white transition-colors"
          >
            Close
          </button>
        )}
        {onDownload && report.status === 'COMPLETED' && (
          <button
            onClick={() => onDownload(report.id)}
            className="flex-1 btn-primary flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download {report.data?.format || 'PDF'}
          </button>
        )}
      </div>
    </div>
  );
};
